import { StyleSheet } from 'react-native';
import { AppTheme } from '../../theme';

export const GAME_CARD_WIDTH = 74;
export const GAME_CARD_ACTIVE_WIDTH = 84;

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollContent: {
      paddingBottom: 24,
    },

    // ── Compact hero header ─────────────────────────────────────────
    hero: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 12,
      marginTop: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 14,
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.primary + '33',
    },
    heroIcon: {
      width: 38,
      height: 38,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary + '22',
      marginRight: 10,
    },
    heroBody: { flex: 1 },
    heroTitle: {
      fontSize: 14,
      fontWeight: '900',
      color: theme.text,
      letterSpacing: 0.6,
    },
    heroSub: {
      fontSize: 10,
      color: theme.subText,
      marginTop: 1,
      fontWeight: '600',
    },
    heroPill: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      backgroundColor: theme.success + '1F',
      borderWidth: 1,
      borderColor: theme.success + '55',
    },
    heroPillText: {
      fontSize: 9,
      fontWeight: '900',
      color: theme.success,
      letterSpacing: 0.5,
    },

    // ── Section headers (tight) ─────────────────────────────────────
    sectionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      marginTop: 12,
      marginBottom: 7,
    },
    sectionTitle: {
      fontSize: 11,
      fontWeight: '800',
      color: theme.text,
      letterSpacing: 1.1,
      marginLeft: 6,
    },
    sectionSpacer: { flex: 1 },
    sectionHint: {
      fontSize: 9.5,
      fontWeight: '800',
      color: theme.subText,
      letterSpacing: 0.4,
    },
    stepBadge: {
      minWidth: 20,
      height: 20,
      borderRadius: 6,
      paddingHorizontal: 5,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 6,
      backgroundColor: theme.primary + '1F',
      borderWidth: 1,
      borderColor: theme.primary + '44',
    },
    stepBadgeText: {
      fontSize: 10,
      fontWeight: '900',
      color: theme.primary,
    },

    // ── Game carousel ───────────────────────────────────────────────
    gamesContent: {
      paddingHorizontal: 12,
      paddingTop: 4,
      paddingBottom: 4,
      alignItems: 'center',
    },
    gameCard: {
      width: GAME_CARD_WIDTH,
      height: 96,
      borderRadius: 11,
      overflow: 'hidden',
      marginRight: 8,
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.border,
    },
    gameCardActive: {
      width: GAME_CARD_ACTIVE_WIDTH,
      height: 106,
      borderWidth: 2,
      borderColor: theme.primary,
    },
    gameImage: {
      width: '100%',
      height: '100%',
    },
    gameImageOverlay: {
      ...StyleSheet.absoluteFill,
      backgroundColor: 'rgba(0,0,0,0.30)',
    },
    gameNameBar: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingVertical: 4,
      paddingHorizontal: 3,
      backgroundColor: 'rgba(0,0,0,0.62)',
    },
    gameName: {
      fontSize: 9.5,
      fontWeight: '800',
      color: '#fff',
      textAlign: 'center',
    },
    gamePlayersPill: {
      position: 'absolute',
      top: 4,
      right: 4,
      borderRadius: 5,
      paddingHorizontal: 4,
      paddingVertical: 1,
      backgroundColor: 'rgba(0,0,0,0.65)',
    },
    gamePlayersText: {
      fontSize: 8,
      fontWeight: '900',
      color: '#fff',
    },
    gameCheckBadge: {
      position: 'absolute',
      top: 4,
      left: 4,
      width: 17,
      height: 17,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary,
    },

    // ── Location segmented control ──────────────────────────────────
    segRow: {
      flexDirection: 'row',
      marginHorizontal: 12,
      backgroundColor: theme.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 3,
      gap: 3,
    },
    segItem: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 9,
      borderRadius: 9,
      gap: 5,
    },
    segItemActive: {
      backgroundColor: theme.primary + '1F',
      borderWidth: 1,
      borderColor: theme.primary + '66',
    },
    segLabel: {
      fontSize: 11,
      fontWeight: '800',
      color: theme.subText,
      letterSpacing: 0.4,
    },
    segLabelActive: {
      color: theme.primary,
    },

    // ── Shop picker ─────────────────────────────────────────────────
    shopCard: {
      marginHorizontal: 12,
      marginTop: 8,
      backgroundColor: theme.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    shopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 7,
      paddingHorizontal: 6,
      borderRadius: 9,
    },
    shopRowActive: {
      backgroundColor: theme.primary + '14',
    },
    shopIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary + '18',
      marginRight: 9,
    },
    shopInfo: { flex: 1 },
    shopName: {
      fontSize: 12,
      fontWeight: '800',
      color: theme.text,
    },
    shopMeta: {
      fontSize: 9.5,
      color: theme.subText,
      marginTop: 1,
      fontWeight: '600',
    },
    shopEmpty: {
      fontSize: 10.5,
      color: theme.subText,
      paddingVertical: 8,
      paddingHorizontal: 6,
      lineHeight: 15,
    },

    // ── Generic option cards (mode / wager) ─────────────────────────
    optionRow: {
      flexDirection: 'row',
      paddingHorizontal: 12,
      gap: 8,
    },
    optionCard: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.card,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.border,
      paddingVertical: 10,
      paddingHorizontal: 9,
      gap: 8,
    },
    optionCardActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primary + '14',
    },
    optionCardDisabled: {
      opacity: 0.4,
    },
    optionIcon: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.statCard,
    },
    optionBody: { flex: 1 },
    optionLabel: {
      fontSize: 11.5,
      fontWeight: '800',
      color: theme.text,
    },
    optionLabelMuted: {
      color: theme.subText,
    },
    optionSub: {
      fontSize: 9.5,
      color: theme.subText,
      marginTop: 1,
      fontWeight: '600',
    },
    optionSubActive: {
      color: theme.primary,
    },

    // ── Compact pills (series format) ───────────────────────────────
    pillRow: {
      flexDirection: 'row',
      paddingHorizontal: 12,
      gap: 8,
    },
    pill: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 9,
      borderRadius: 11,
      backgroundColor: theme.card,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    pillActive: {
      borderColor: theme.primary,
      backgroundColor: theme.primary + '1A',
    },
    pillText: {
      fontSize: 13,
      fontWeight: '900',
      color: theme.text,
    },
    pillTextActive: {
      color: theme.primary,
    },
    pillSub: {
      fontSize: 9,
      fontWeight: '700',
      color: theme.subText,
      marginTop: 1,
    },
// ── Party player-count stepper ──────────────────────────────────
    stepperCard: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 12,
      marginTop: 8,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 12,
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.border,
    },
    stepperLabel: {
      flex: 1,
      fontSize: 11,
      fontWeight: '800',
      color: theme.text,
      letterSpacing: 0.4,
    },
    stepperBtn: {
      width: 30,
      height: 30,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary + '1A',
      borderWidth: 1,
      borderColor: theme.primary + '55',
    },
    stepperValue: {
      minWidth: 34,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepperValueText: {
      fontSize: 15,
      fontWeight: '900',
      color: theme.primary,
    },

    // ── Wager method cards ──────────────────────────────────────────
    wagerRow: {
      flexDirection: 'row',
      paddingHorizontal: 12,
      gap: 7,
    },
    wagerCard: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 11,
      paddingHorizontal: 4,
      borderRadius: 12,
      backgroundColor: theme.card,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    wagerIcon: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 5,
      backgroundColor: theme.statCard,
    },
    wagerLabel: {
      fontSize: 10.5,
      fontWeight: '900',
      color: theme.text,
      textAlign: 'center',
    },
    wagerSub: {
      fontSize: 8.5,
      fontWeight: '700',
      color: theme.subText,
      textAlign: 'center',
      marginTop: 1,
    },

    // ── Amount input + quick chips ──────────────────────────────────
    amountRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      marginTop: 9,
      gap: 8,
    },
    amountWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      height: 44,
      borderRadius: 11,
      borderWidth: 1.5,
      borderColor: theme.success + '66',
      backgroundColor: theme.success + '12',
      paddingHorizontal: 10,
    },
    amountCurrency: {
      fontSize: 15,
      fontWeight: '900',
      color: theme.success,
      marginRight: 5,
    },
    amountInput: {
      flex: 1,
      fontSize: 15,
      fontWeight: '800',
      color: theme.text,
      paddingVertical: 6,
    },
    quickRow: {
      flexDirection: 'row',
      paddingHorizontal: 12,
      marginTop: 8,
      gap: 7,
    },
    quickChip: {
      flex: 1,
      height: 32,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.statCard,
      borderWidth: 1,
      borderColor: theme.border,
    },
    quickChipActive: {
      backgroundColor: theme.success + '1F',
      borderColor: theme.success,
    },
    quickChipText: {
      fontSize: 11.5,
      fontWeight: '800',
      color: theme.text,
    },
    quickChipTextActive: {
      color: theme.success,
    },
    balanceHint: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      marginTop: 8,
      gap: 5,
    },
    balanceText: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.subText,
    },
    balanceValue: {
      fontSize: 10,
      fontWeight: '900',
      color: theme.success,
    },

    // ── Detail cards (escrow / wager summary) ───────────────────────
    detailCard: {
      marginHorizontal: 12,
      marginTop: 9,
      borderRadius: 12,
      borderWidth: 1,
      padding: 10,
      backgroundColor: theme.card,
      borderColor: theme.border,
    },
    detailTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 5,
    },
    detailTitle: {
      fontSize: 10.5,
      fontWeight: '900',
      letterSpacing: 0.7,
      marginLeft: 6,
    },
    detailDesc: {
      fontSize: 10,
      color: theme.subText,
      lineHeight: 15,
    },
    selectRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 7,
      borderRadius: 9,
      paddingHorizontal: 4,
      marginTop: 3,
    },
    selectRowActive: {
      backgroundColor: theme.primary + '14',
    },
    selectAvatar: {
      width: 28,
      height: 28,
      borderRadius: 14,
      marginRight: 9,
    },
    selectInfo: { flex: 1 },
    selectName: {
      fontSize: 12,
      fontWeight: '800',
      color: theme.text,
    },
    selectStatus: {
      fontSize: 9,
      fontWeight: '700',
      color: theme.success,
      marginTop: 1,
    },

    // ── Opponents ───────────────────────────────────────────────────
    inviteRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      gap: 8,
    },
    inviteWrap: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      height: 42,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.inputBackground,
      paddingHorizontal: 10,
      gap: 7,
    },
    inviteInput: {
      flex: 1,
      fontSize: 12.5,
      fontWeight: '700',
      letterSpacing: 1.6,
      color: theme.text,
      paddingVertical: 6,
    },
    inviteBtn: {
      height: 42,
      paddingHorizontal: 16,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary,
    },
    inviteBtnText: {
      fontSize: 11.5,
      fontWeight: '900',
      color: '#fff',
      letterSpacing: 0.5,
    },
    inviteBtnDisabled: {
      opacity: 0.5,
    },

    opponentCard: {
      marginHorizontal: 12,
      marginTop: 9,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.card,
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    opponentHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 4,
      paddingVertical: 4,
      gap: 5,
    },
    opponentTitle: {
      fontSize: 10,
      fontWeight: '900',
      color: theme.text,
      letterSpacing: 0.8,
    },
    opponentCount: {
      marginLeft: 'auto',
      fontSize: 9.5,
      fontWeight: '800',
      color: theme.success,
    },
    opponentEmpty: {
      fontSize: 10,
      color: theme.subText,
      paddingHorizontal: 4,
      paddingVertical: 6,
      lineHeight: 15,
    },
    playerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 6,
      paddingHorizontal: 4,
      borderRadius: 9,
    },
    playerAvatar: {
      width: 30,
      height: 30,
      borderRadius: 15,
      marginRight: 9,
    },
    playerInfo: { flex: 1 },
    playerName: {
      fontSize: 12,
      fontWeight: '800',
      color: theme.text,
    },
    playerMeta: {
      fontSize: 9,
      color: theme.subText,
      marginTop: 1,
      fontWeight: '600',
    },
    addBtn: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: theme.primary,
      backgroundColor: theme.primary + '1A',
    },
    addBtnAdded: {
      backgroundColor: theme.success,
      borderColor: theme.success,
    },

    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      paddingHorizontal: 12,
      gap: 6,
      marginTop: 8,
    },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: 8,
      paddingRight: 6,
      paddingVertical: 5,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.primary,
      backgroundColor: theme.primary + '1A',
      gap: 4,
    },
    chipText: {
      fontSize: 11,
      fontWeight: '800',
      color: theme.primary,
    },

    // ── Info box ────────────────────────────────────────────────────
    infoBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginHorizontal: 12,
      marginTop: 9,
      padding: 9,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: theme.info + '44',
      backgroundColor: theme.info + '12',
      gap: 7,
    },
    infoText: {
      flex: 1,
      fontSize: 10,
      color: theme.subText,
      lineHeight: 15,
      fontWeight: '600',
    },

    // ── Notifications toggle ────────────────────────────────────────
    toggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 12,
      marginTop: 10,
      paddingVertical: 9,
      paddingHorizontal: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.card,
    },
    toggleIcon: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.info + '18',
      marginRight: 9,
    },
    toggleBody: { flex: 1 },
    toggleTitle: {
      fontSize: 11.5,
      fontWeight: '800',
      color: theme.text,
    },
    toggleSub: {
      fontSize: 9,
      color: theme.subText,
      marginTop: 1,
      fontWeight: '600',
    },
    switch: {
      transform: [{ scaleX: 0.82 }, { scaleY: 0.82 }],
    },

    // ── Start button ────────────────────────────────────────────────
    startBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 12,
      marginTop: 14,
      height: 52,
      borderRadius: 14,
      backgroundColor: theme.primary,
      gap: 8,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.35,
      shadowRadius: 10,
      elevation: 6,
    },
    startBtnDisabled: {
      backgroundColor: theme.border,
      shadowOpacity: 0,
      elevation: 0,
    },
    startBtnText: {
      fontSize: 14.5,
      fontWeight: '900',
      color: '#fff',
      letterSpacing: 1,
    },
    startHint: {
      textAlign: 'center',
      fontSize: 9.5,
      fontWeight: '700',
      color: theme.subText,
      marginTop: 6,
      paddingHorizontal: 12,
    },

    // ── Created-match summary ───────────────────────────────────────
    summaryCard: {
      marginHorizontal: 12,
      marginTop: 12,
      padding: 12,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: theme.success + '66',
      backgroundColor: theme.success + '12',
    },
    summaryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      marginBottom: 8,
    },
    summaryTitle: {
      flex: 1,
      fontSize: 12,
      fontWeight: '900',
      color: theme.success,
      letterSpacing: 0.6,
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 3,
    },
    summaryLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.subText,
    },
    summaryValue: {
      fontSize: 11,
      fontWeight: '800',
      color: theme.text,
    },
    inviteCodeValue: {
      fontSize: 13,
      letterSpacing: 2.5,
      color: theme.primary,
    },
    summaryActions: {
      flexDirection: 'row',
      marginTop: 10,
      gap: 8,
    },
    ghostBtn: {
      flex: 1,
      height: 40,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: theme.primary,
      backgroundColor: 'transparent',
    },
    ghostBtnText: {
      fontSize: 11.5,
      fontWeight: '900',
      color: theme.primary,
      letterSpacing: 0.5,
    },
    rematchBtn: {
      flex: 1,
      height: 40,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.success,
      flexDirection: 'row',
      gap: 6,
    },
    rematchBtnText: {
      fontSize: 11.5,
      fontWeight: '900',
      color: '#fff',
      letterSpacing: 0.5,
    },

    // ── Header pieces ───────────────────────────────────────────────
    headerLeftRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: 8,
    },
    headerBackBtn: {
      padding: 4,
      marginRight: 2,
    },
    headerRightRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: 12,
    },
    headerAvatar: {
      width: 26,
      height: 26,
      borderRadius: 13,
      marginLeft: 10,
      borderWidth: 1.5,
      borderColor: theme.primary,
    },
    headerTitleText: {
      fontSize: 17,
      fontWeight: '900',
      color: theme.text,
      letterSpacing: 0.8,
    },
    headerTitleAccent: {
      color: theme.primary,
    },
  });
