import { StyleSheet } from 'react-native';
import { AppTheme } from '../../theme';

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    content: {
      padding: 16,
      paddingBottom: 40,
    },

    // ── Hero ────────────────────────────────────────────────────────
    hero: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      padding: 12,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.primary + '33',
      backgroundColor: theme.card,
      marginBottom: 14,
    },
    heroIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary + '22',
    },
    heroBody: { flex: 1 },
    heroTitle: {
      fontSize: 14,
      fontWeight: '900',
      color: theme.text,
      letterSpacing: 0.6,
    },
    heroSub: {
      fontSize: 10.5,
      lineHeight: 15,
      color: theme.subText,
      fontWeight: '600',
      marginTop: 2,
    },

    // ── Code entry ──────────────────────────────────────────────────
    label: {
      fontSize: 10.5,
      fontWeight: '900',
      color: theme.text,
      letterSpacing: 0.8,
      marginBottom: 7,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    inputWrap: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      height: 56,
      borderRadius: 13,
      borderWidth: 1.5,
      borderColor: theme.primary + '66',
      backgroundColor: theme.inputBackground,
      paddingHorizontal: 12,
      gap: 8,
    },
    input: {
      flex: 1,
      fontSize: 20,
      fontWeight: '900',
      letterSpacing: 5,
      color: theme.text,
      paddingVertical: 6,
    },
    joinBtn: {
      height: 56,
      paddingHorizontal: 20,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary,
    },
    joinBtnDisabled: { opacity: 0.5 },
    joinBtnText: {
      fontSize: 13,
      fontWeight: '900',
      color: '#fff',
      letterSpacing: 0.8,
    },
    hint: {
      fontSize: 10,
      lineHeight: 15,
      color: theme.subText,
      fontWeight: '600',
      marginTop: 8,
    },
    errorBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      marginTop: 10,
      padding: 9,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: theme.error + '66',
      backgroundColor: theme.error + '14',
    },
    errorText: {
      flex: 1,
      fontSize: 10.5,
      lineHeight: 15,
      color: theme.error,
      fontWeight: '700',
    },

    // ── Joined match card ───────────────────────────────────────────
    resultCard: {
      marginTop: 16,
      padding: 14,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: theme.success + '66',
      backgroundColor: theme.success + '12',
    },
    resultHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      marginBottom: 10,
    },
    resultTitle: {
      flex: 1,
      fontSize: 12.5,
      fontWeight: '900',
      color: theme.success,
      letterSpacing: 0.6,
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 4,
      gap: 10,
    },
    rowLabel: {
      fontSize: 10.5,
      fontWeight: '700',
      color: theme.subText,
    },
    rowValue: {
      flexShrink: 1,
      fontSize: 11.5,
      fontWeight: '800',
      color: theme.text,
      textAlign: 'right',
    },
    codeBadge: {
      paddingHorizontal: 10,
      paddingVertical: 3,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.primary,
      backgroundColor: theme.primary + '14',
    },
    codeBadgeText: {
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 2.5,
      color: theme.primary,
    },
    playersRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 4,
    },
    playerChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
      backgroundColor: theme.statCard,
    },
    playerName: {
      fontSize: 10.5,
      fontWeight: '800',
      color: theme.text,
    },
    actions: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 14,
    },
    primaryBtn: {
      flex: 1,
      height: 46,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: theme.primary,
    },
    primaryBtnText: {
      fontSize: 12,
      fontWeight: '900',
      color: '#fff',
      letterSpacing: 0.6,
    },
    ghostBtn: {
      flex: 1,
      height: 46,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1.5,
      borderColor: theme.primary,
      backgroundColor: 'transparent',
    },
    ghostBtnText: {
      fontSize: 12,
      fontWeight: '900',
      color: theme.primary,
      letterSpacing: 0.6,
    },
    note: {
      fontSize: 10,
      lineHeight: 15,
      color: theme.subText,
      fontWeight: '600',
      marginTop: 10,
    },
  });
