import { StyleSheet, Platform } from 'react-native';
import { AppTheme } from '../../theme';

export const createStyles = (theme: AppTheme, topInset: number = 0) =>
  StyleSheet.create({
    scroll: {
      flex: 1,
      backgroundColor: 'transparent',
    },
    scrollContent: {
      paddingBottom: 32,
    },

    // ── Welcome Header ──────────────────────────────────────────
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: topInset + (Platform.OS === 'ios' ? 8 : 12),
      paddingBottom: 16,
      backgroundColor: 'transparent',
    },
    avatarWrapper: {
      position: 'relative',
      marginRight: 12,
    },
    headerAvatar: {
      width: 56,
      height: 56,
      borderRadius: 28,
      borderWidth: 2,
      borderColor: theme.primary,
    },
    onlineDot: {
      position: 'absolute',
      bottom: 2,
      right: 2,
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: theme.success,
      borderWidth: 2,
      borderColor: theme.background,
    },
    welcomeBlock: {
      flex: 1,
      paddingVertical: 8,
      paddingRight: 8,
      gap: 3,
    },
    welcomeSmall: {
      fontSize: 11,
      color: theme.subText,
      letterSpacing: 1.8,
      fontWeight: '600',
    },
    welcomeName: {
      fontSize: 26,
      fontWeight: 'bold',
      color: theme.warning,
      letterSpacing: 1,
      lineHeight: 30,
    },
    welcomeSub: {
      fontSize: 12,
      color: theme.subText,
      marginTop: 1,
    },
    notifBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: theme.card,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
    },

    // ── Action Cards ─────────────────────────────────────────────
    actionRow: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      marginBottom: 16,
      gap: 12,
    },
    actionCard: {
      flex: 1,
      borderRadius: 22,
      padding: 18,
      paddingBottom: 22,
      borderWidth: 1,
      minHeight: 186,
      overflow: 'hidden',
      position: 'relative',
    },
    actionCardCyan: {
      borderColor: theme.primary,
      backgroundColor: theme.primary + '14',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 6 },
      // shadowOpacity: 0.4,
      // shadowRadius: 12,
      // elevation: 8,
    },
    actionCardPurple: {
      borderColor: theme.secondary,
      backgroundColor: theme.secondary + '14',
      // shadowColor: theme.secondary,
      shadowOffset: { width: 0, height: 6 },
      // shadowOpacity: 0.4,
      // shadowRadius: 12,
      // elevation: 8,
    },
    // Decorative oversized circle in the bottom-right corner
    actionDecoCyan: {
      position: 'absolute',
      bottom: -34,
      right: -20,
      width: 110,
      height: 110,
      borderRadius: 55,
      backgroundColor: theme.primary + '22',
    },
    actionDecoPurple: {
      position: 'absolute',
      bottom: -34,
      right: -20,
      width: 110,
      height: 110,
      borderRadius: 55,
      backgroundColor: theme.secondary + '22',
    },
    actionIconBadge: {
      width: 54,
      height: 54,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 14,
      borderWidth: 1,
    },
    actionIconBadgeCyan: {
      backgroundColor: theme.primary + '22',
      borderColor: theme.primary,
    },
    actionIconBadgePurple: {
      backgroundColor: theme.secondary + '22',
      borderColor: theme.secondary,
    },
    actionTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.text,
      letterSpacing: 0.5,
      marginBottom: 4,
    },
    actionSubtitle: {
      fontSize: 12,
      color: theme.subText,
      lineHeight: 18,
      fontWeight: '500',
      paddingRight: 38,
    },
    actionArrowCyan: {
      position: 'absolute',
      bottom: 16,
      right: 16,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.4,
      shadowRadius: 6,
      elevation: 4,
    },
    actionArrowPurple: {
      position: 'absolute',
      bottom: 16,
      right: 16,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.secondary,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.secondary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.4,
      shadowRadius: 6,
      elevation: 4,
    },
    actionTag: {
      position: 'absolute',
      top: 14,
      right: 14,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 10,
      backgroundColor: theme.card,
    },
    actionTagText: {
      fontSize: 9,
      fontWeight: 'bold',
      letterSpacing: 1.2,
    },
    actionTagCyan: {
      color: theme.primary,
    },
    actionTagPurple: {
      color: theme.secondary,
    },

    // ── Join-by-code entry (compact row under the action cards) ───
    joinCard: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 16,
      marginBottom: 16,
      padding: 14,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.success,
      backgroundColor: theme.success + '12',
    },
    joinCardIcon: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.success + '22',
      borderWidth: 1,
      borderColor: theme.success,
      marginRight: 12,
    },
    joinCardBody: { flex: 1 },
    joinCardTitle: {
      fontSize: 14,
      fontWeight: 'bold',
      color: theme.text,
      letterSpacing: 0.4,
    },
    joinCardSub: {
      fontSize: 11,
      color: theme.subText,
      fontWeight: '600',
      marginTop: 2,
      lineHeight: 15,
    },
    joinCardArrow: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: theme.success,
      alignItems: 'center',
      justifyContent: 'center',
    },

    // ── Full-width section cards ──────────────────────────────────
    sectionCard: {
      marginHorizontal: 16,
      marginBottom: 16,
      borderRadius: 16,
      padding: 16,
      borderColor: theme.card,
      backgroundColor: theme.card + '12',
    },

    // Section card header row (title + VIEW ALL)
    colHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 14,
    },
    colTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    colTitle: {
      fontSize: 12,
      fontWeight: 'bold',
      color: theme.text,
      letterSpacing: 1,
      marginLeft: 5,
    },
    viewAllText: {
      fontSize: 11,
      color: theme.primary,
      fontWeight: '700',
    },

    // Live Activity items (full width — bigger thumbs)
    activityItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      backgroundColor: theme.card + '12',
    },
    activityThumb: {
      width: 56,
      height: 56,
      borderRadius: 12,
      marginRight: 14,
      backgroundColor: theme.statCard,
    },
    activityInfo: {
      flex: 1,
    },
    activityUsername: {
      fontSize: 14,
      fontWeight: 'bold',
      color: theme.text,
    },
    activityAction: {
      fontSize: 13,
      color: theme.subText,
      marginTop: 2,
      lineHeight: 18,
    },
    activityGame: {
      fontSize: 11,
      color: theme.primary,
      fontWeight: '600',
      marginTop: 3,
    },
    activityTime: {
      fontSize: 11,
      color: theme.subText,
      marginLeft: 8,
      textAlign: 'right',
    },

    // Quick Stats (full-width card)
    statsTitle: {
      fontSize: 12,
      fontWeight: 'bold',
      color: theme.text,
      letterSpacing: 1,
      marginBottom: 14,
    },
    statsInnerRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 16,
    },
    statsHalfCol: {
      flex: 1,
      backgroundColor: theme.statCard,
      borderRadius: 14,
      padding: 12,
    },
    streakLabel: {
      fontSize: 10,
      color: theme.subText,
      letterSpacing: 0.8,
      marginBottom: 4,
    },
    streakRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    streakNumber: {
      fontSize: 32,
      fontWeight: 'bold',
      color: theme.text,
      marginRight: 5,
      lineHeight: 36,
    },
    streakSub: {
      fontSize: 10,
      color: theme.subText,
      marginTop: 2,
      letterSpacing: 0.5,
    },
    rankLabel: {
      fontSize: 10,
      color: theme.subText,
      letterSpacing: 0.8,
      marginBottom: 6,
    },
    rankNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    rankNameText: {
      fontSize: 13,
      fontWeight: 'bold',
      color: theme.info,
      marginLeft: 4,
      letterSpacing: 0.3,
    },
    rankBar: {
      height: 8,
      backgroundColor: theme.border,
      borderRadius: 4,
      overflow: 'hidden',
      marginBottom: 4,
    },
    rankBarFill: {
      height: '100%',
      backgroundColor: theme.info,
      borderRadius: 4,
    },
    rankRpText: {
      fontSize: 10,
      color: theme.subText,
      letterSpacing: 0.3,
    },
    miniStatsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      borderTopWidth: 1,
      borderTopColor: theme.border,
      paddingTop: 14,
    },
    miniStat: {
      flex: 1,
      alignItems: 'center',
    },
    miniStatValue: {
      fontSize: 14,
      fontWeight: 'bold',
      color: theme.text,
      marginTop: 4,
      letterSpacing: 0.3,
    },
    miniStatLabel: {
      fontSize: 10,
      color: theme.subText,
      marginTop: 2,
      letterSpacing: 0.5,
      textAlign: 'center',
    },

    // ── Featured Tournament ──────────────────────────────────────
    featuredCard: {
      marginHorizontal: 16,
      marginBottom: 24,
      borderRadius: 16,
      overflow: 'hidden',
      minHeight: 176,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.rankGold,
      backgroundColor: theme.card,
    },
    featuredBgImage: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      width: '100%',
      height: '100%',
    },
    featuredOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.68)',
    },
    featuredBody: {
      flex: 1,
      padding: 18,
      paddingRight: 10,
      zIndex: 1,
    },
    liveBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(52,199,89,0.2)',
      borderWidth: 1,
      borderColor: theme.success,
      borderRadius: 12,
      paddingHorizontal: 9,
      paddingVertical: 4,
      alignSelf: 'flex-start',
      marginBottom: 10,
    },
    liveDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.success,
      marginRight: 6,
    },
    liveBadgeText: {
      fontSize: 10,
      fontWeight: 'bold',
      color: theme.success,
      letterSpacing: 0.8,
    },
    featuredTitle: {
      fontSize: 19,
      fontWeight: 'bold',
      color: '#fff',
      letterSpacing: 0.5,
      marginBottom: 3,
    },
    featuredSubtitle: {
      fontSize: 11,
      color: 'rgba(255,255,255,0.7)',
      lineHeight: 16,
      marginBottom: 12,
    },
    prizeLabel: {
      fontSize: 10,
      color: 'rgba(255,255,255,0.6)',
      letterSpacing: 1,
    },
    prizeAmount: {
      fontSize: 24,
      fontWeight: 'bold',
      color: theme.rankGold,
      marginBottom: 12,
    },
    joinBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.primary,
      paddingHorizontal: 16,
      paddingVertical: 9,
      borderRadius: 10,
      alignSelf: 'flex-start',
    },
    joinBtnText: {
      fontSize: 13,
      fontWeight: 'bold',
      color: '#fff',
      marginRight: 5,
      letterSpacing: 0.5,
    },
    featuredBadge: {
      width: 78,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1,
    },
    featuredBadgeBox: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(212,175,55,0.15)',
      borderWidth: 1,
      borderColor: theme.rankGold,
      borderRadius: 12,
      padding: 11,
    },
    featuredBadgeText: {
      fontSize: 11,
      fontWeight: 'bold',
      color: theme.rankGold,
      textAlign: 'center',
      marginTop: 5,
      letterSpacing: 1,
      lineHeight: 15,
    },
  });
